### ISSUE TITLE
Cannot use NFS mountpoint for scan directory

### ISSUE THREAD

**Issue by blaxer** [hooram/ownphotos-frontend#37]
So I am quite the noob at this sort of thing so please go easy on me but I have an NFS mountpoint to my photos directory (which is on Unraid). I then bind that directory to the /data directory in the container but ownphotos will not "see" or scan this directory. I can verify that I am able to read and write to the mountpoint on the physical host machine and inside the ownphotos-backend container. When I go to edit the scan directory in this configuration nothing happens, I don't get the directory listing, if I type something into the directory text box it will not save. Looking at the developer console, when trying to update the scan directory location I see 400 bad request errors. I do not see anything that seems relevant in any of the log files that ownphotos is saving. Thank you in advance for your assistance.

**Comment by blaxer** [comment]
Added GUID and PUID to the container environment variables and now it's working, not sure why though.

**Comment by guysoft** [comment]
You can do something like this with ``docker-compose.yml``.
This is how to use nfs volume using docker.

```
version: '3.6'

services:
  ownphotos-backend:
    image: hooram/ownphotos
    volumes:
      - type: volume
        source: git
        target: /code/protected_media
        volume:
          nocopy: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_IP},nolock,soft,rw"
      device: ":/nfs_mount"

```

Note: 
Please use the docker-compose.yml and set up your settings. I am just giving an example of how to use nfs with docker-compose.
